name: Android 12 5.10
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions

on:
  workflow_call:  # This allows this workflow to be called from another workflow
  
jobs:
  build-kernel-a12-5-10-kernelsu-susfs:
    strategy:
      fail-fast: false
      matrix:
        include:
        - sub_level: "66"
          os_patch_level: "2022-01"
          revision: "r11"
        - manifest: "oneplus12_v.xml "
          gki: "gki-android14-6.1"
            
    uses: ./.github/workflows/test.yml
    with:
      android_version: "android12"
      m: ${{ matrix.manifest }}
      gki: ${{ matrix.gki }}
