name: 开始引用
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions

on:
  workflow_dispatch:  # This allows this workflow to be called from another workflow
  
jobs:
  build_kernel:
    strategy:
      matrix:
        include:
        - manifest: "oneplus12_v.xml"
          gki: "gki-android14-6.1"
        - manifest: "oneplus_13r.xml"
          gki: "gki-android14-6.1"
        - manifest: "oneplus_ace3_pro_v.xml"
          gki: "gki-android14-6.1"
        - manifest: "oneplus_ace5.xml"
          gki: "gki-android14-6.1"
        - manifest: "oneplus_pad2_v.xml"
          gki: "gki-android14-6.1"
            
    uses: ./.github/workflows/test.yml
    with:
      m: ${{ matrix.manifest }}
      gki: ${{ matrix.gki }}
    secrets: inherit