name: 测试一键编译
permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
        ksuV:
            description: '选择你要编译的KSU版本'
            required: true
            default: 'KERNELSU-NEXT'
            type: choice
            options:
            - KERNELSU-NEXT
            - MKSU
        VER:
            description: '如6.1.66[输入框中的内容]（可留空）'
            required: false
            type: string
jobs:
  build_kernel_ksun:
    strategy:
      matrix:
        include:
        - manifest: "oneplus12_v.xml"
          gki: "gki-android14-6.1"
          model: "oneplus/sm8650"
    if: ${{ inputs.ksuV == 'KERNELSU-NEXT' }}        
    uses: ./.github/workflows/test.yml
    with:
      m: ${{ matrix.manifest }}
      gki: ${{ matrix.gki }}
      model: ${{ matrix.model }}
      ksu: ${{ inputs.ksuV }} 
      ver: ${{ inputs.VER }} 
    secrets: inherit

  build_kernel_mksu:
    strategy:
      matrix:
        include:
        - manifest: "oneplus12_v.xml"
          gki: "gki-android14-6.1"
          model: "oneplus/sm8650"
    if: ${{ inputs.ksuV == 'MKSU' }}        
    uses: ./.github/workflows/run.yml
    with:
      m: ${{ matrix.manifest }}
      gki: ${{ matrix.gki }}
      model: ${{ matrix.model }}
    #   ksu: ${{ inputs.ksuV }} 
    #   ver: ${{ inputs.VER }} 
    secrets: inherit